[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor_exam = "6VbBHa1qUhrbaaYTqDQbgxFSs4D1XDJ2G7PJm96uwVQo"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
